CREATE TABLE "HR"."MEMBER" 
   (   "USERID" VARCHAR2(15 BYTE), 
   "PASSWORD" VARCHAR2(21 BYTE), 
   "USERNAME" VARCHAR2(12 BYTE) CONSTRAINT "MEMBER_NAME_NN" NOT NULL ENABLE, 
   "GENDER" VARCHAR2(1 BYTE), 
   "EMAIL" VARCHAR2(50 BYTE), 
   "POINT" NUMBER(5,0) DEFAULT 100, 
   "REGISTERDATE" DATE DEFAULT sysdate, 
    CHECK (gender in ('m', 'f')) ENABLE, 
    CONSTRAINT "MEMBER_USERID_PK" PRIMARY KEY ("USERID"));
     
     
create table Friends(
    friendNo number,
    FRIENDNAME VARCHAR2(50),
    FRIENDMOBILE VARCHAR2(50),
    FRIENDADDRESS VARCHAR2(50),
    PRIMARY KEY (friendNo)
);